# fly.toml app configuration file generated for scrumstorypoints-svelte on 2025-05-03T13:20:40-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scrumstorypoints-svelte'
primary_region = 'den'

[build]
  dockerfile = "Dockerfile"

[build.args]
  PUBLIC_POCKETBASE_URL = "http://localhost:8090"
  PUBLIC_POCKETBASE_ADMIN = "http://localhost:8090/_"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = "pb_data"
  destination = "/pb/pb_data"

[env]
  PORT = "3000" # SvelteKit listens on this port
  PUBLIC_POCKETBASE_URL="http://localhost:8090/"
  PUBLIC_POCKETBASE_ADMIN="http://localhost:8090/_"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1