# fly.toml app configuration file generated for scrumstorypoints-pb on 2025-05-06T14:20:18-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scrumstorypoints-pb'
primary_region = 'den'


[mounts]
  source = 'pb_data'
  destination = '/pb_data'

# optional if you want to change the PocketBase version
[build.args]
  PB_VERSION="0.27.2"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  [http_service.concurrency]
    type = "requests"
    soft_limit = 500
    hard_limit = 550

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
